# | export

class NoConfigCompanyError(Exception):
    def __init__(self, sql, domo_instance):
        message = f'SQL "{sql}" returned no results in {domo_instance}'
        self.message = message
        super().__init__(self.message)


async def _retrieve_company_ds(config_auth: dmda.DomoAuth,
                               dataset_id: str,
                               sql: str,
                               debug_prn: bool = False,
                               debug_api: bool = False,
                               logger: lc.Logger = None) -> pd.DataFrame:

    logger = lc.Logger(app_name='_retrieve_company_ds')

    ds = await dmds.DomoDataset.get_from_id(auth=config_auth,
                                            dataset_id=dataset_id, debug_api=debug_api)

    message = f"⚙️ START - Retrieving company list \n{ds.display_url()} using \n{sql}}"
    
    logger.log_info(message, debug_prn = debug_prn)

    df = await ds.query_dataset_private(auth=config_auth,
                                        dataset_id=dataset_id,
                                        sql=sql,
                                        debug_api=debug_api)
    if len(df.index) == 0:
        raise NoConfigCompanyError(
            sql, domo_instance=config_auth.domo_instance)
    
    message = f"\n⚙️ SUCCESS 🎉 Retrieved company list \nThere are {len(df.index)} companies to update"
        logger.log_info(message, debug_prn = debug_prn)


    if logger:
        logger.log_info(
            f"\n⚙️ SUCCESS 🎉 Retrieved company list \nThere are {len(df.index)} companies to update")
    
    return df
