async def get_domains_with_global_config_auth(config_auth: dmda.DomoAuth,
                                              dataset_id: str,
                                              global_auth: dmda.DomoAuth,
                                              exception_auth: dmda.DomoAuth,
                                              sql: str = "select domain from table",
                                              debug_api: bool = False,
                                              logger: lc.Logger = None) -> pd.DataFrame:

    

    for index, instance in df.iterrows():
        creds = global_auth

        if instance['config_exception_pw'] == 1:
            creds = exception_auth

        full_auth = dmda.DomoFullAuth(domo_instance=instance['domo_instance'],
                                      domo_username=creds.domo_username,
                                      domo_password=creds.domo_password)
        try:
            await full_auth.get_auth_token(debug=False)

        except dmda.InvalidCredentialsError as e:
            print(e)
            if logger : 
                logger.log_error(f"Error with Invalid Credentials {instance} instance. Exception : {e}")
        
        df.at[index, 'instance_auth'] = full_auth
        df.at[index, 'is_valid'] = 1 if (full_auth.token) else 0

    return df